###############################################################################
# Default Prompt 
###############################################################################
format = '''
$all
'''

right_format = """
$conda\
$cmd_duration\
$time
"""

[directory]
truncation_length = -1
truncate_to_repo = true
truncation_symbol = ' '

[time]
disabled = false
format = ' [$time]($style) '
style = 'bold blue'

[cmd_duration]
format = ' [$duration]($style) 羽'

[conda]
format = ' [\($environment\)]($style)'

###############################################################################
# Language Specific 
###############################################################################
[cmake]
format = "via [$symbol]($style)"

[golang]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'
